# This is a basic workflow to help you get started with Actions
name: Banff Python script

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      #install dependncies 
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Runs a single command using the runners shell
      - name: Run the banff script 
        env: 
          CBC_CLIENT_ID: ${{ secrets.CBC_CLIENT_ID }}
          CBC_CLIENT_SECRET: ${{ secrets.CBC_CLIENT_SECRET }}
        run: python banff.py
