name: Update Banff

on:
  schedule:
    - cron: "0 * * * *"  # Run every hour

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Choose your Python version

    - name: Run Python script
      run: |
        banff.py  # Replace with the actual filename of your Python script
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
